development:
  adapter: postgresql
  database: supermarket_development
  host: localhost
  pool: 30
  port: 5433

test:
  adapter: postgresql
  database: supermarket_test
  host: localhost
  port: 5433

production:
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  adapter: postgresql
  database: supermarket_production
  port: 5433
